services:
  - type: web
    name: reproductor-de-musica-daniel
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: commit
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
